name: Code Analysis

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint isort flake8
        python -m pip install DXEntity PyYAML tabulate
    - name: Lint check
      continue-on-error: false
      run: |
        pylint $(git ls-files "*.py")
    - name: Running flake8
      continue-on-error: false
      run: |
        flake8 $(git ls-files "*.py")
    - name: Checking imports
      continue-on-error: false
      run: |
        isort --check $(git ls-files "*.py")
